env:
  node: true
  es6: true
  browser: true

ecmaFeatures:
  modules: true

rules:
  no-debugger: 2
  no-dupe-args: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  no-ex-assign: 2
  no-unreachable: 2
  valid-typeof: 2
  no-fallthrough: 2
  quotes: [2, "single", "avoid-escape"]
  indent: [2, 2]
  comma-spacing: 2
  semi: [2, "never"]
  space-infix-ops: 2
  space-return-throw-case: 2
  space-before-function-paren: [2, {named: "never"}]
  space-before-blocks: [2, "always"]
  new-parens: 2
  max-len: [2, 100, 2]
  no-multiple-empty-lines: [2, {max: 2}]
  eol-last: 2
  no-trailing-spaces: 2
  space-after-keywords: 2
  prefer-const: 2
  strict: [2, "global"]
  no-undef: 2

globals:
  $: true
